server:
  port: ${SPRING_PORT:8081}
spring:
  application:
    name: debuglab-redis-cache-service
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 2s
      connect-timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 1
  session:
    store-type: redis
    timeout: 30m
